package org.example.spring2025demo3rest.pojos;

import jakarta.persistence.*;

/**
 * Represents an automobile entity associated with a user.
 * Each Auto record includes details such as make, model, year, and the owning user.
 */
@Entity // This tells Hibernate to make a table out of this class
public class Auto {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)  /* Primary key for the Auto table. Auto-generated by the database. */
    private Integer id;
    private String make;
    private String model;
    private Integer year;

    /**
     * The user who owns this automobile.
     * Many Autos can be associated with one User.
     */
    @ManyToOne
    @JoinColumn(name="user_id")
    private User user;      //User can have many homes - this will maintain the relationship

    /**
     * Gets the ID of the auto.
     * @return auto ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the ID of the auto.
     * @param id auto ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Gets the make of the auto.
     * @return auto make
     */
    public String getMake() {
        return make;
    }

    /**
     * Sets the make of the auto.
     * @param make auto make
     */
    public void setMake(String make) {
        this.make = make;
    }

    /**
     * Gets the model of the auto.
     * @return auto model
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the model of the auto.
     * @param model auto model
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Gets the year the auto was manufactured.
     * @return auto year
     */
    public Integer getYear() {
        return year;
    }

    /**
     * Sets the manufacturing year of the auto.
     * @param year auto year
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * Gets the user associated with this auto.
     * @return the user who owns the auto
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the user associated with this auto.
     * @param user the user to associate
     */
    public void setUser(User user) {
        this.user = user;
    }
}
